#!/usr/bin/env python
import sys, os
server_ip = None
if os.getenv("SSH_CONNECTION"):
	# set broadway backend in remote connection
	os.environ["GDK_BACKEND"] = 'broadway'
	from_ip, from_port, server_ip, server_port = os.getenv("SSH_CONNECTION").split()

if os.getenv("GDK_BACKEND") == 'broadway':
	# These modules can crash application.
	# Because they use x11 specific backend directly.
	for name in ("GTK_MODULES", "UBUNTU_MENUPROXY",):
		if name in os.environ:
			del os.environ[name]
	os.environ["LIBOVERLAY_SCROLLBAR"] = '0'
	os.environ["GTK_IM_MODULE"] = 'ibus'
	display = os.environ.get("BROADWAY_DISPLAY", "8080")

	if not server_ip:
		# XXX
		server_ip = "localhost"
	print "open http://%s:%s with your browser"%(server_ip, display)

import gi
gi.require_version("Gtk", "3.0")
from gi.repository import GLib, GObject, Gtk

default_hook = sys.excepthook
def abuild_excepthook(exc_type, exc_obj, exc_tb):
	if exc_type is KeyboardInterrupt:
		Gtk.main_quit()
	return default_hook(exc_type, exc_obj, exc_tb)

sys.excepthook = abuild_excepthook

if __name__ == '__main__':
	from MainWindow import MainWindow
	import utils
	win = MainWindow()

	for directory in (os.environ.get('TOP', ''), os.getcwd()):
		if directory and win.set_source_top(directory):
			win.set_choose_directory(directory)
			break

	GLib.timeout_add(400, lambda: True)
	Gtk.main()
